# Generated by Django 3.0.8 on 2020-07-03 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20200703_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='magnitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='score',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='confidence',
            field=models.FloatField(null=True),
        ),
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True)),
                ('score', models.FloatField()),
                ('mangitude', models.FloatField()),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Feedback')),
            ],
        ),
    ]
