# Generated by Django 3.0.8 on 2020-07-03 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20200703_1651'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sentence',
            old_name='mangitude',
            new_name='magnitude',
        ),
    ]
