# Generated by Django 3.0.8 on 2020-07-03 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20200703_2215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='analyzed',
        ),
        migrations.AlterField(
            model_name='feedback',
            name='magnitude',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='score',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
