# Generated by Django 3.0.8 on 2020-07-04 09:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_auto_20200704_0847'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='last_update',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='camera',
            name='x',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='camera',
            name='y',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='RoomVisitors',
        ),
    ]
