# Generated by Django 3.0.8 on 2020-07-04 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_auto_20200704_0926'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='mq',
            field=models.FloatField(default=0),
        ),
    ]
